[project]
authors = ["IsaacMercado <mercadoluis095@gmail.com>"]
channels = ["conda-forge"]
name = "pixi-hello-world"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pymc = { version = ">=5.28.1,<6", channel = "conda-forge" }
ipykernel = ">=6.29.5,<7"
seaborn = { version = ">=0.13.2,<0.14", channel = "conda-forge" }
ipywidgets = ">=8.1.7,<9"
cmdstan = { version = ">=2.36.0,<3", channel = "conda-forge" }
cmdstanpy = { version = ">=1.2.5,<2", channel = "conda-forge" }
astroquery = { version = ">=0.4.10,<0.5", channel = "conda-forge" }
astropy = { version = ">=7.1.0,<8", channel = "conda-forge" }
pymc-extras = { version = ">=0.10.0,<0.11", channel = "conda-forge" }
notebook = ">=7.4.4,<8"
polars = { version = ">=1.39.3,<2", channel = "conda-forge" }
nutpie = { version = ">=0.16.8,<0.17", channel = "conda-forge" }
pyro-ppl = { version = ">=1.9.1,<2", channel = "conda-forge" }
pytorch = { version = ">=2.7.1,<3", channel = "conda-forge" }
python-graphviz = { version = ">=0.21,<0.22", channel = "conda-forge" }
pandas = { version = ">=2.3.3,<3", channel = "conda-forge" }
arviz = { version = ">=0.22.0,<0.23", channel = "conda-forge" }
r = ">=4.5,<4.6"
r-ggplot2 = ">=4.0.1,<5"
funsor = ">=0.4.5,<0.5"

[pypi-dependencies]
tensorflow = "==2.21.0"
tensorflow-probability = "==0.25.0"
tf-keras = "==2.21.0"
jax = { version = ">=0.7.0, <0.8", extras = ["cpu"] }
numpyro = ">=0.20.0, <0.21"
blackjax = ">=1.2.5, <2"
